site_name: My Docs
docs_dir: 'docs'
repo_url: https://github.com/mindspore-courses/step_into_llm
repo_name: mindspore-courses/step_into_llm
edit_uri: edit/main/docs/

site_author: Contributors
copyright: Licensed under Creative Commons Attribution-NonCommercial 4.0 International License.

theme:
  name: material
  font: false
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs

# Customization
extra_css:
  - '_static/css/extra.css?v=14'
  
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes

# Navigation
nav:
  - Home: 
    - Home: index.md
    - MindNLP: MindNLP.md
  - step_into_chatgpt: 
    - Transformer: step_into_chatgpt/Transformer.md
    - BERT: step_into_chatgpt/BERT.md
  - step_into_llm: 
    - ChatGLM: step_into_llm/ChatGLM.md
  - others:
    - set_env: others/Ascend-910A-NPU-driver-firmware-CANN-suite-MindSpore.md

# Plugins
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          site_name: Step into LLM
          build: true
        - locale: zh
          name: 中文
          site_name: 走进大语言模型
          build: true
      nav_translations:
        zh:
          - Home: 主页
          - MindNLP: MindNLP用法
          - step_into_chatgpt: 走进ChatGPT
          - Transformer: Transformer
          - BERT: BERT
          - step_into_llm: 走进LLM
          - ChatGLM: ChatGLM
          - others: 其他
          - set_env: 环境配置
          
  - with-pdf:
      #author: Contributors
      #copyright: Licensed under Creative Commons Attribution-NonCommercial 4.0 International License.
        
      cover: true
      back_cover: true
      cover_title: TITLE TEXT
      cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
        
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #   - 'release-notes/:upgrading'
      #   - 'release-notes/:changelog'

      #exclude_pages:
      #   - 'bugs/'
      #   - 'appendix/contribute/'
      #convert_iframe:
      #   - src: IFRAME SRC
      #     img: POSTER IMAGE URL
      #     text: ALTERNATE TEXT
      #   - src: ...
      #two_columns_level: 3
        
      #render_js: true
      #headless_chrome_path: headless-chromium
      
      #enabled_if_env: ENABLE_PDF_EXPORT
        
      #debug_html: true
      #show_anchors: true
      #verbose: true
